# Generated by Django 4.0.4 on 2022-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
