# Generated by Django 4.0.4 on 2022-04-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='keyword',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='permissioned_to',
            field=models.BooleanField(default=True),
        ),
    ]
