# Generated by Django 4.0.4 on 2022-04-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_keyword_file_permission_file_permissioned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='status',
            new_name='public',
        ),
    ]
